name: automerge auto-cherry-picked pr's

on:
  pull_request_target:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
  
jobs:
#   find-the-prt-comment:
#     name: Find the prt comment on the pr
#     if: contains(github.event.pull_request.labels.*.name, 'Auto_Cherry_Picked')
#     runs-on: ubuntu-latest
#     outputs:
#       prt_comment: ${{steps.fc.outputs.comment-body}}
#     steps:
#       - name: Find the prt comment
#         uses: peter-evans/find-comment@v2
#         id: fc
#         with:
#           issue-number: ${{ github.event.number }}
#           body-includes: "trigger: test-robottelo"
#           direction: last
#           token: ${{ secrets.SATQE }}

  automerge:
    name: Automerge auto-cherry-picked pr
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'Auto_Cherry_Picked')
    steps:
      - name: 'Wait for status checks'
        id: wait-for-status-checks
        uses: "WyriHaximus/github-action-wait-for-status@v1.7.1"
        with:
          checkInterval: 30
        env:
          GITHUB_TOKEN: ${{ secrets.SATQE }}

      - id: automerge
        name: automerge the cherry-picked pr
        uses: "pascalgn/automerge-action@v0.15.5"
        if: steps.waitforstatuschecks.outputs.status == 'success'
        env:
          GITHUB_TOKEN: "${{ secrets.SATQE }}"
          MERGE_LABELS: "automerge, Auto_Cherry_Picked"
          MERGE_METHOD: "squash"
          MERGE_RETRIES: 5
          MERGE_RETRY_SLEEP: 30000

