name: Auto Assign

on:
  pull_request:
    types:
      - opened
      - reopened

jobs:
  add-assignees:
    name: Add author to assignee
    if: "!contains(github.event.pull_request.labels.*.name, 'Auto_Cherry_Picked')"
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v1.2.4
        with:
          configuration-path: '.github/auto_assign.yml'
