name: automerge auto-cherry-picked pr's
on:
  pull_request_target:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
    branches-ignore:
      - main
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}

jobs:
  automerge:
    name: Automerge auto-cherry-picked pr
    runs-on: ubuntu-latest
    steps:
      - id: find-prt-comment
        name: Find the prt comment
        uses: peter-evans/find-comment@v2
        with:
          issue-number: ${{ github.event.number }}
          body-includes: "trigger: test-robottelo"
          direction: last

 automerge:
    needs: find-the-prt-comment
    name: Automerge auto-cherry-picked pr
    runs-on: ubuntu-latest
    if: needs.find-the-parent-prt-comment.outputs.prt_comment != '[]'
    steps:
#       - name: 'Wait for status checks'
#         id: wait-for-status-checks
#         uses: "WyriHaximus/github-action-wait-for-status@v1.7.1"
#         with:
#           checkInterval: 300
#         env:
#           GITHUB_TOKEN: "${{ secrets.SATQE }}"

      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@v0.15.5"
        env:
          GITHUB_TOKEN: "${{ secrets.SATQE }}"
          MERGE_LABELS: "automerge, Auto_Cherry_Picked"
          MERGE_METHOD: "squash"
          MERGE_RETRIES: 5
          MERGE_RETRY_SLEEP: 900000

      - name: provide the feedback about the automerge result if failed
        if: steps.automerge.outputs.mergeResult != 'merged'
        run: |
          echo "Pull request ${{ steps.automerge.outputs.pullRequestNumber }} failed !"
          echo "It is failed because of ${{steps.automerge.outputs.mergeResult}}"
          exit 1

      - name: provide the feedback about the automerge result id passed
        if: steps.automerge.outputs.mergeResult == 'merged'
        run: |
          echo "Pull request ${{ steps.automerge.outputs.pullRequestNumber }} merged!"

