name: 'automerge auto-cherry-picked pr'
# on:
#   pull_request_target:
#     types:
#       - labeled
#       - unlabeled
#       - synchronize
#       - opened
#       - edited
#       - ready_for_review
#       - reopened
#     branches-ignore:
#       - main
#   pull_request_review:
#     types:
#       - submitted
#   check_suite:
#     types:
#       - completed
#   status: {}

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '*/5 * * * *'
  
jobs:
  automerge:
    name: Automerge auto-cherry-picked pr
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'Auto_Cherry_Picked')
    steps:
      - id: automerge
        name: automerge the cherry-picked pr
        uses: "pascalgn/automerge-action@v0.15.5"
        if: steps.waitforstatuschecks.outputs.status == 'success'
        env:
          GITHUB_TOKEN: "${{ secrets.SATQE }}"
          MERGE_LABELS: "automerge, Auto_Cherry_Picked"
          MERGE_METHOD: "squash"
          MERGE_RETRIES: 5
          MERGE_RETRY_SLEEP: 30000

