name: "Auto Merge"
on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
      - edited
      - labeled
      - unlabeled
      - ready_for_review
    


jobs:
  auto-merge:
    name: Auto Merge
    runs-on: ubuntu-latest
    steps:
      - uses: reitermarkus/automerge@v2
        with:
          token: ${{ secrets.SATQE }}
          merge-method: squash
          required-labels: 'automerge,Auto_Cherry_Picked'
          pull-request: ${{ github.event.inputs.pull-request }}
