name: Automerge workflow

on:
  check_suite:
    types:
      - completed
  pull_request:
    branches-ignore:
      - main
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  status: {}

  
jobs:
  automerge:
    name: Automerge auto-cherry-picked pr
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'Auto_Cherry_Picked')
    steps:
      - id: automerge
        name: automerge the cherry-picked pr
        uses: "pascalgn/automerge-action@v0.15.5"
        env:
          GITHUB_TOKEN: "${{ secrets.SATQE }}"
          MERGE_LABELS: "automerge, Auto_Cherry_Picked"
          MERGE_METHOD: "squash"
          MERGE_RETRIES: 5
          MERGE_RETRY_SLEEP: 30000

