
name: Google chat notification

on:
  issues:
    types: [ opened, reopened ]

jobs:
  Google_Chat_Notification:
    runs-on: ubuntu-latest
    steps:
    - name: Google Chat Notification - Robottelo
      uses: Co-qn/google-chat-notification@releases/v1
      with:
        name: "${{ github.event.issue.title }}"
        url: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
        status: failure
