
name: Testing Github Action 

on: [pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Something that might fail
        run: exit 1
      - name: Create Issue on Failed workflow
        if: ${{ failure() }}
        uses: dacbd/create-issue-action@main
        with:
          token: ${{ github.token }}
          title: Auto-Cherry-Pick workflow failed for PR #${{ github.event.number }}
          body: |
            #### Auto-Cherry-Pick Failure:
            
            [Failed Run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
            
            [Codebase](https://github.com/${{ github.repository }}/tree/${{ github.sha }})
            
            Workflow Name - `${{ github.workflow }}`
            
            Job -           `${{ github.job }}`
            
            Status -        `${{ job.status }}`

          labels: auto-cherry-pick-failed
          assignees: "${{ github.event.pull_request.user.login }}"
