
name: Testing Github Action 

on:
  pull_request_target:
    types:
      - closed

jobs:
  auto-cherry-pick:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Failing this Step
        run: exit 0
  
  create-issue:
    runs-on: ubuntu-latest
    if: ${{ always() && contains(join(needs.*.result, ','), 'failure') }}
    needs: auto-cherry-pick
    steps:
      - name: Create Issue on Failed workflow
        uses: dacbd/create-issue-action@main
        with:
          token: ${{ github.token }}
          title: "[Failed-AutoCherryPick] - ${{ github.event.pull_request.title }}"
          body: |
            #### Auto-Cherry-Pick WorkFlow Failure:

            - [Failed Cherrypick Action](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})

            - [Parent Pull Request](https://github.com/${{ github.repository }}/pull/${{ github.event.number }})

          labels: Failed_AutoCherryPick
          assignees: "${{ github.event.pull_request.assignee.login }}"

  google-chat-notification:
    runs-on: ubuntu-latest
    if: ${{ always() && contains(join(needs.*.result, ','), 'failure') }}
    needs: auto-cherry-pick
    steps:
      - name: Google Chat Notification - Robottelo
        uses: Co-qn/google-chat-notification@releases/v1
        with:
          name: "[Failed-AutoCherryPick] - ${{ github.event.pull_request.title }}"
          url: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
          status: failure

          
          
          
