
name: Testing Github Action

on:
  pull_request_target:
    types:
      - closed

jobs:

  find-the-last-prt-comment:
    name: Find last prt comment & save for auto-cherry-pick pr's
    runs-on: ubuntu-latest
    outputs:
      prt_comment: ${{steps.fc.outputs.comment-body}}
    steps:
      - name: Find Comment
        uses: peter-evans/find-comment@v2
        id: fc
        with:
          issue-number: ${{ github.event.number }}
          body-includes: "trigger: test-robottelo"

  auto-cherry-pick:
    name: Auto Cherry Pick to previous branch
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'CherryPick')
    runs-on: ubuntu-latest
    env:
      PR_AUTHOR: ${{ github.event.pull_request.user.login }}
      TO_BRANCH: "6.11.z"
    outputs:
      pr_number: ${{steps.issue.outputs.number}}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Cherry pick into ${{ env.TO_BRANCH }}
        uses: omkarkhatavkar/github-cherry-pick-action@output_pr
        id: issue
        with:
          author: ${{ env.PR_AUTHOR }} <${{ env.PR_AUTHOR }}@users.noreply.github.com>
          token: ${{ secrets.SATQE }}
          branch: ${{ env.TO_BRANCH }}
          labels: |
            Auto_Cherry_Picked
            ${{ env.TO_BRANCH }}
          assignees: "${{ github.event.pull_request.assignee.login }}"
      - run: |
          echo "${{ steps.issue.outputs.number }}"
     

  add-prt-comment:
    name: Add prt comment into Cherrypick Pr's
    runs-on: ubuntu-latest
    needs: [auto-cherry-pick, find-the-last-prt-comment]
    steps:
      - uses: mshick/add-pr-comment@v2
        with:
          issue: ${{ needs.auto-cherry-pick.outputs.pr_number }}
          message: |
            ${{needs.find-the-last-prt-comment.outputs.prt_comment}}
          repo-token: ${{ secrets.SATQE }}


  create-issue:
    runs-on: ubuntu-latest
    if: ${{ always() && contains(join(needs.*.result, ','), 'failure') }}
    needs: auto-cherry-pick
    outputs:
      issue_url: ${{steps.create_issue.outputs.html_url}}
    steps:
      - name: Create Issue on Failed workflow
        id: create_issue
        uses: dacbd/create-issue-action@main
        with:
          token: ${{ github.token }}
          title: "[Failed-AutoCherryPick] - ${{ github.event.pull_request.title }}"
          body: |
            #### Auto-Cherry-Pick WorkFlow Failure:

            - [Failed Cherrypick Action](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})

            - [Parent Pull Request](https://github.com/${{ github.repository }}/pull/${{ github.event.number }})

          labels: Failed_AutoCherryPick
          assignees: "${{ github.event.pull_request.assignee.login }}"



  google-chat-notification:
    runs-on: ubuntu-latest
    if: ${{ always() && contains(join(needs.auto-cherry-pick.result, ','), 'failure') }}
    needs: [auto-cherry-pick, create-issue]
    steps:
      - name: Google Chat Notification - Robottelo
        uses: omkarkhatavkar/google-chat-notification@add_author_name
        with:
          name: "${{ github.event.pull_request.title }}"
          url: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
          issue_url: ${{ needs.create-issue.outputs.issue_url }}
          status: failure

