
name: Testing Github Action 

on:
  pull_request_target:
    types:
      - closed

jobs:

  auto-cherry-pick:
    name: Auto Cherry Pick to previous branch
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'CherryPick')
    runs-on: ubuntu-latest
    env:
      PR_AUTHOR: ${{ github.event.pull_request.user.login }}
      TO_BRANCH: "6.11.z"
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Cherry pick into ${{ env.TO_BRANCH }}
        uses: omkarkhatavkar/github-cherry-pick-action@output_pr
        id: issue
        with:
          author: ${{ env.PR_AUTHOR }} <${{ env.PR_AUTHOR }}@users.noreply.github.com>
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ env.TO_BRANCH }}
          labels: |
            Auto_Cherry_Picked
            ${{ env.TO_BRANCH }}
          assignees: "${{ github.event.pull_request.assignee.login }}"
      - run: |
          echo "${{ steps.issue.outputs.number }}"

  create-issue:
    runs-on: ubuntu-latest
    if: ${{ always() && contains(join(needs.*.result, ','), 'failure') }}
    needs: auto-cherry-pick
    steps:
      - name: Create Issue on Failed workflow
        uses: dacbd/create-issue-action@main
        with:
          token: ${{ github.token }}
          title: "[Failed-AutoCherryPick] - ${{ github.event.pull_request.title }}"
          body: |
            #### Auto-Cherry-Pick WorkFlow Failure:

            - [Failed Cherrypick Action](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})

            - [Parent Pull Request](https://github.com/${{ github.repository }}/pull/${{ github.event.number }})

          labels: Failed_AutoCherryPick
          assignees: "${{ github.event.pull_request.assignee.login }}"



  google-chat-notification:
    runs-on: ubuntu-latest
    if: ${{ always() && contains(join(needs.*.result, ','), 'failure') }}
    needs: auto-cherry-pick
    steps:
      - name: Google Chat Notification - Robottelo
        uses: Co-qn/google-chat-notification@releases/v1
        with:
          name: "${{ github.event.pull_request.title }}"
          url: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
          status: failure
  
  find-the-last-prt-comment:
    runs-on: ubuntu-latest
    if: ${{ always() && contains(join(needs.*.result, ','), 'failure') }}
    needs: auto-cherry-pick
    steps:
      - name: Find Comment
        uses: peter-evans/find-comment@v2
        id: fc
        with:
          issue-number: ${{ github.event.number }}
          body-includes: "trigger: test-robottelo"
      - run: |
          echo ${{ steps.fc.outputs.comment-id }}
          echo ${{ steps.fc.outputs.comment-body }}
          echo ${{ steps.fc.outputs.comment-author }}

          
          
          
